server:
  servlet:
    jsp:
      init-parameters:
        development: true
spring:
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
    static-path-pattern: /static/**
  web:
    resources:
      static-locations:
        classpath:/static/
      add-mappings: true
  devtools:
    livereload:
      enabled: true
  datasource:
    url:
      jdbc:mysql://brokurly-mysql.cibbkywj3asc.ap-northeast-2.rds.amazonaws.com:3306/cs?useUnicode=true\&characterEncoding=utf8&useSSL=false&serverTimezone=UTC&autoReconnection=true
    username: 
      root
    password:
      brokurly1!
    driver-class-name: 
      com.mysql.cj.jdbc.Driver
  jpa:
    database: 
      mysql
    generate-ddl: 
      true
    hibernate:
      ddl-auto: 
        none
    show-sql: 
      true
    properties:
      hibernate:
        format_sql:
          true
    