server:
  servlet:
    jsp:
      init-parameters:
        development: true
spring:
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
    static-path-pattern: /static/**
  profiles:
    include:
      secret
  web:
    resources:
      static-locations:
        classpath:/static/
      add-mappings: true
  devtools:
    livereload:
      enabled: true
  jpa:
    database: 
      mysql
    generate-ddl: 
      false
    hibernate:
      ddl-auto: 
        none
    show-sql: 
      true
    properties:
      hibernate:
        format_sql:
          true